name: Test Minecraft recompilation
# started from https://github.com/sschr15/vineflower-testing
on:
  workflow_dispatch:
    inputs:
      vf_branch:
        description: 'Vineflower branch to test'
        required: true
        default: 'develop/1.10.0'
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: mache

      - name: Clone Vineflower
        uses: actions/checkout@v3
        with:
          repository: Vineflower/Vineflower
          ref: ${{ github.event.inputs.vf_branch }}
          path: vineflower

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Build Vineflower
        run: |
          cd vineflower
          # Setting the STATUS is used to easily identify the build from multiple output jars
          STATUS=snapshot ./gradlew publishtomavenlocal -x test

      - name: Decompile Minecraft
        run: |
          cd mache
          ./gradlew applyPatches

      - name: Try to build
        continue-on-error: true
        run: |
          cd mache
          ( ./gradlew build 3>&1 1>&2- 2>&3- ) | tee build-log.txt

      - uses: actions/upload-artifact@v3
        with:
          name: build-log
          path: mache/build-log.txt

      - uses: actions/upload-artifact@v3
        with:
          name: decompile-log
          path: mache/versions/*/build/mache/input/decomp.jar.log

      - run: |
          cd mache
          regex="([0-9]+) errors"
          if [[ $(cat build-log.txt) =~ $regex ]] then
            echo "# Re-compile errors" >> $GITHUB_STEP_SUMMARY
            echo "${BASH_REMATCH[1]} errors found" >> $GITHUB_STEP_SUMMARY
          fi
